### ISSUE TITLE
Update Dockerfile node:version

### ISSUE THREAD

**Issue by anthonyronda** [sanity-io/github-action-sanity#7]
This action is currently pulling `node:12`.

v12 EOL is 2022-04-30. Source: https://endoflife.date/nodejs

Also worth updating the URLs in your labels 🙂

**Comment by stitch-james** [comment]
This is now causing the action to fail, as the latest sanity CLI requires a more recent version of node:

```
  error @sanity/cli@3.0.0-dev-preview.11: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.22.12"
  error Found incompatible module.
```

**Comment by geball** [comment]
Thank you both. `v0.4` has now been released and uses Node 14.
